version: "3.7"


services:
  web-server:
    container_name: '${APP_NAME}-server'
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./www/:/var/www/html/"
    ports:
      - "8101:80"


  mysql-server:
    container_name: '${APP_NAME}-db'
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "8102:80"


  phpmyadmin:
    container_name: '${APP_NAME}-phpadmin'
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: '${PHPADMIN_USER}'
      PMA_PASSWORD: '${PHPADMIN_PASS}'
    ports:
      - "5000:80"


volumes:
  mysql-data: